name: mongo-sharding-repl

include:
  - path:
      - ./generated-sharding.yaml

services:
  mongodb-configsvr:
    container_name: mongodb-configsvr
    image: dh-mirror.gitverse.ru/mongo:latest
    command:
      [
        "--configsvr",
        "--replSet",
        "config_rs",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    networks:
      - bf-network
    volumes:
      - mongodb_configsvr_container:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  mongodb-router:
    container_name: mongodb-router
    image: dh-mirror.gitverse.ru/mongo:latest
    depends_on:
      - mongodb-configsvr
    command: [
      "mongos",
      "--configdb",
      "config_rs/mongodb-configsvr:27017",
      "--bind_ip_all",
      "--port",
      "27017"
    ]
    networks:
      - bf-network
    volumes:
      - mongodb_router_container:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379"
    volumes:
      - redis_container:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [
      "redis-server",
      "/usr/local/etc/redis/redis.conf"
    ]
    networks:
      - bf-network

  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - mongodb-router
    ports:
      - 8080:8080
    networks:
      - bf-network
    environment:
      REDIS_URL: "redis://redis:6379"
      MONGODB_URL: "mongodb://mongodb-router"
      MONGODB_DATABASE_NAME: "somedb"

volumes:
  mongodb_router_container:
  mongodb_configsvr_container:
  redis_container:

networks:
  bf-network:
    name: bf-network
    driver: bridge
